import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { CQL_SYSTEM_PROMPT, generateUserPrompt, postProcessCQL } from '@/lib/cql-generator';
import type { MeasureRequirement } from '@/types/cql';

// Initialize Anthropic client
const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

interface ExtendedRequirements extends Partial<MeasureRequirement> {
  existingCQL?: string;
  validationErrors?: string;
  fixMode?: boolean;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const requirements: ExtendedRequirements = body.requirements;

    // Handle fix mode
    if (requirements.fixMode && requirements.existingCQL && requirements.validationErrors) {
      return await handleFixMode(requirements);
    }

    if (!requirements || !requirements.purpose) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Generate the user prompt
    const userPrompt = generateUserPrompt(requirements);

    // Call Claude API
    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      system: CQL_SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: userPrompt,
        },
      ],
    });

    // Extract the generated CQL
    const responseContent = message.content[0];
    if (responseContent.type !== 'text') {
      throw new Error('Unexpected response format');
    }

    const rawCQL = responseContent.text;
    const processedCQL = postProcessCQL(rawCQL);

    // Generate suggestions based on the measure type
    const suggestions = generateSuggestions(requirements);

    return NextResponse.json({
      cql: processedCQL,
      suggestions,
    });
  } catch (error) {
    console.error('CQL generation error:', error);

    // Return a fallback CQL template on error
    const fallbackCQL = generateFallbackCQL(
      (await request.json().catch(() => ({ requirements: {} }))).requirements
    );

    return NextResponse.json({
      cql: fallbackCQL,
      suggestions: [
        'Generated using fallback template due to API error',
        'Review and customize the logic for your specific use case',
      ],
      error: 'Used fallback template',
    });
  }
}

function generateSuggestions(requirements: Partial<MeasureRequirement>): string[] {
  const suggestions: string[] = [];

  if (requirements.measureType === 'clinical-quality') {
    suggestions.push('Consider adding Supplemental Data Elements (SDE) for CMS reporting');
    suggestions.push('Ensure hospice and palliative care exclusions are included');
  }

  if (requirements.scoringType === 'proportion') {
    suggestions.push('Verify the denominator and numerator definitions align with your measure intent');
  }

  if (!requirements.evidenceReferences || requirements.evidenceReferences.length === 0) {
    suggestions.push('Consider adding clinical evidence references to strengthen measure validity');
  }

  if (requirements.valueSets && requirements.valueSets.length < 3) {
    suggestions.push('You may need additional value sets for comprehensive population identification');
  }

  suggestions.push('Test the CQL against Synthea-generated patient data');
  suggestions.push('Validate with VS Code CQL extension before production use');

  return suggestions;
}

function generateFallbackCQL(requirements: Partial<MeasureRequirement>): string {
  const libraryName = requirements.purpose
    ? requirements.purpose
        .replace(/[^a-zA-Z0-9\s]/g, '')
        .split(/\s+/)
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .slice(0, 4)
        .join('')
    : 'NewMeasure';

  const year = new Date().getFullYear();
  const valueSetsSection = requirements.valueSets
    ? requirements.valueSets
        .map(
          (vs) =>
            `valueset "${vs.name}": 'http://cts.nlm.nih.gov/fhir/ValueSet/${vs.oid}'`
        )
        .join('\n')
    : '// Add value sets here';

  return `/*
 * ${requirements.purpose || 'Clinical Quality Measure'}
 * ${requirements.problemStatement || ''}
 *
 * Generated by CQL Builder
 * Based on HL7 CQL v1.5.3 and CQF Measures IG
 */
library ${libraryName} version '1.0.0'

using FHIR version '4.0.1'

include FHIRHelpers version '4.0.1' called FHIRHelpers
include SupplementalDataElements version '3.0.0' called SDE

${valueSetsSection}

parameter "Measurement Period" Interval<DateTime>
  default Interval[@${year}-01-01T00:00:00.0, @${year + 1}-01-01T00:00:00.0)

context Patient

// Supplemental Data Elements
define "SDE Ethnicity":
  SDE."SDE Ethnicity"

define "SDE Payer":
  SDE."SDE Payer"

define "SDE Race":
  SDE."SDE Race"

define "SDE Sex":
  SDE."SDE Sex"

/*
 * Initial Population
 * Define the patients eligible for this measure
 */
define "Initial Population":
  // TODO: Define initial population criteria
  true

/*
 * Denominator
 * Typically equals Initial Population for proportion measures
 */
define "Denominator":
  "Initial Population"

/*
 * Denominator Exclusions
 * Patients to exclude from the denominator
 */
define "Denominator Exclusions":
  false

/*
 * Numerator
 * Patients meeting the measure criteria
 */
define "Numerator":
  // TODO: Define numerator criteria
  true

/*
 * Numerator Exclusions
 * Patients to exclude from the numerator
 */
define "Numerator Exclusions":
  false
`;
}

async function handleFixMode(requirements: ExtendedRequirements) {
  const fixPrompt = `You are a CQL (Clinical Quality Language) expert. Fix the following CQL code that has validation errors.

## Current CQL Code (with errors):
\`\`\`cql
${requirements.existingCQL}
\`\`\`

## Validation Errors to Fix:
${requirements.validationErrors}

## Instructions:
1. Analyze each error and understand what's wrong
2. Fix ALL the errors while preserving the measure's intent
3. Ensure the fixed code follows HL7 CQL v1.5.3 specification
4. Keep all the business logic intact
5. Return ONLY the complete fixed CQL code, no explanations

Common fixes to consider:
- Missing or incorrect FHIRHelpers include
- Incorrect FHIR path expressions
- Missing context statement
- Incorrect interval syntax
- Type mismatches in comparisons
- Missing or incorrect library/version declarations
- Incorrect value set references

Return the complete fixed CQL library code.`;

  try {
    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      messages: [
        {
          role: 'user',
          content: fixPrompt,
        },
      ],
    });

    const responseContent = message.content[0];
    if (responseContent.type !== 'text') {
      throw new Error('Unexpected response format');
    }

    const rawCQL = responseContent.text;
    const processedCQL = postProcessCQL(rawCQL);

    return NextResponse.json({
      cql: processedCQL,
      suggestions: ['CQL has been auto-fixed based on validation errors'],
    });
  } catch (error) {
    console.error('Auto-fix error:', error);
    return NextResponse.json(
      { error: 'Failed to auto-fix CQL' },
      { status: 500 }
    );
  }
}
